{% set version = "1.1.0" %}

package:
  name: elevation
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/elevation/elevation-{{ version }}.tar.gz
  sha256: 935f0bdc488df5f6187177b2d946e9322262eac4a8d643956ca82d7012dd7c55

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - eio=elevation.cli:eio

requirements:
  host:
    - python
    - pip
  run:
    - python
    - appdirs
    - click <7.0
    - fasteners
    - future

test:
  imports:
    - elevation
  commands:
    - eio --help

about:
  home: http://elevation.bopen.eu
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python script to download global terrain digital elevation models, SRTM 30m DEM and SRTM 90m DEM

extra:
  recipe-maintainers:
    - ocefpaf
