{% set name = "elevation" %}
{% set version = "1.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elevation-{{ version }}.tar.gz
  sha256: be27446562e7964f7d8fa78c4829dbbb8ac43df405ad09be8c49633adb8f4877

build:
  number: 0
  noarch: python
  entry_points:
    - eio=elevation.cli:eio
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - appdirs
    - click
    - fasteners
    - future

test:
  imports:
    - elevation
  commands:
    - pip check
    - eio --help
  requires:
    - pip

about:
  home: http://elevation.bopen.eu
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python script to download global terrain digital elevation models, SRTM 30m DEM and SRTM 90m DEM

extra:
  recipe-maintainers:
    - ocefpaf
