schema_version: 1

context:
  name: elevation
  version: 1.1.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/elevation-${{ version }}.tar.gz
  sha256: be27446562e7964f7d8fa78c4829dbbb8ac43df405ad09be8c49633adb8f4877

build:
  number: 3
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - eio=elevation.cli:eio

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=42
    - wheel
    - setuptools_scm >=3.4
    - setuptools_scm_git_archive
    - pip
  run:
    - python >=${{ python_min }}
    - appdirs
    - click
    - fasteners

tests:
  - python:
      imports:
        - elevation
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - eio --help

about:
  homepage: https://github.com/bopen/elevation
  license: Apache-2.0
  license_file: LICENSE
  summary: Python script to download global terrain digital elevation models, SRTM 30m DEM and SRTM 90m DEM
  documentation: http://elevation.bopen.eu

extra:
  recipe-maintainers:
    - ocefpaf
    - thewchan
